apiVersion: apps/v1
kind: Deployment
metadata:
  name: stsperfmem-1
  labels:
    app: stsperfmem-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stsperfmem-1
  template:
    metadata:
      labels:
        app: stsperfmem-1
    spec:
      containers:
      - name: stsperfmem-1
        image: busybox
        command:
        - "sleep"
        - "300000"
