apiVersion: apps/v1
kind: Deployment
metadata:
  name: law-deployment
  labels:
    app: law
spec:
  replicas: 1
  selector:
    matchLabels:
      app: law
  template:
    metadata:
      labels:
        app: law
    spec:
      containers:
      - name: law
        image: till/law:1.0
        ports:
        - containerPort: 443
